// <auto-generated />
using EcommApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250218090128_u")]
    partial class u
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcommApp.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrdreAffichage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Mobile",
                            OrdreAffichage = "1"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Ordinateur",
                            OrdreAffichage = "2"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Périphériques",
                            OrdreAffichage = "3"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Périphériques",
                            OrdreAffichage = "4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
